stages:
  - test
  - deploy

test:
    stage: test
    script:
        - pip install -r requirements.txt
        - cd Website
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test

staging:
  stage: deploy

  script:
    - apk update
    - apk add git
    - apk add ruby-dev
    - apk add build-base
    - apk add curl
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh git@github.com
    - git remote add github git@github.com:uofg-cs20/oti-operator.git
    - git push --mirror github
    - gem update --system
    - gem install dpl
    - gem install json
    - gem install bundler
    - dpl --provider=heroku --app=cs20operator --api-key=$HEROKUKEY
    - 
  tags:
    - docker
