stages:
  - test
  - deploy

test:
    stage: test
    script:
        - pip install -r requirements.txt
        - cd Website
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test

staging:
  stage: deploy

  script:
    - apk update
    - apk add git
    - apk add ruby-dev
    - apk add build-base
    - apk add curl
    - gem update --system
    - gem install dpl
    - gem install json
    - gem install bundler
    - dpl --provider=heroku --app=cs20operator --api-key=$HEROKUKEY
  tags:
    - docker
