# Generated by Django 3.0.3 on 2021-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='miptaurl',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
